# Generated by Django 4.0.6 on 2022-07-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task1',
        ),
    ]
